### PR TITLE
remove typing in conda requirements for py>=3.6

### PR DESCRIPTION
**Pull request by fhoehle**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@fhoehle Can you keep this noarch, remove typing and raise the version constraint to `python >=3.6` as we only support Python 3.6+ on conda-forge (for Python 3.x)?

**Comment by fhoehle** [comment]
> @fhoehle Can you keep this noarch, remove typing and raise the version constraint to `python >=3.6` as we only support Python 3.6+ on conda-forge (for Python 3.x)?

@xhochy done

**Comment by xhochy** [comment]
Thanks @fhoehle for taking care of all these `typing` issues.

**Pull request merged**
