### PR TITLE
Update recipe for 0.5.3

### PR DESCRIPTION
**Pull request by cicdw**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cicdw** [comment]
@conda-forge-admin, please rerender

**Comment by cicdw** [comment]
@conda-forge-admin, please rerender

**Comment by cicdw** [comment]
@conda-forge-admin, please rerender

**Comment by cicdw** [comment]
@conda-forge/core this is my first time experiencing an issue with `@conda-forge-admin`, not sure how to proceed from here!

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Heisenbug?

**Comment by cicdw** [comment]
@dhirschfeld i also already merged https://github.com/conda-forge/prefect-feedstock/pull/6 but conda-forge hasn't updated yet - so yea, I think something is up.

**Comment by dhirschfeld** [comment]
It worked for me locally so I thought I'd try again:
```
(smithy) ~\code\github\conda-forge\prefect-feedstock [pr/5]> conda smithy rerender
## CONFIGURATION USED
<SNIP>
Re-rendered with conda-build 3.17.8, conda-smithy 3.3.4, and conda-forge-pinning 2019.05.06
No changes made. This feedstock is up-to-date.
```

Could be it was just an intermittent issue with the service.

**Comment by dhirschfeld** [comment]
I'll go ahead and close this since the other PR has been merged...

**Pull request closed without merging**
