### PR TITLE
Fix for OpenSSL error

### PR DESCRIPTION
**Pull request by Sahiler**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Sahiler** [comment]
Ready for review! 
Changes done
- Adding openssl into `host`

**Comment by madkinsz** [comment]
@Sahiler can you include a blurb on how this will fix the issue? I'm not entirely sure what's going on still.

**Comment by Sahiler** [comment]
Including openssl into host just ensures there is a working installation of openssl when testing out prefect, so it is a work around now that I am looking into it, let me see how I can install it thru conda correctly and update the PR

**Comment by madkinsz** [comment]
Isn't part of the problem that the wrong version is installed?

**Comment by Sahiler** [comment]
@conda-forge-admin rerender

**Comment by Sahiler** [comment]
@conda-forge-admin, please lint

**Comment by Sahiler** [comment]
@madkinsz I managed to find the correct library version and the tests are passing as well, had a weird issue with the linting bot not recognizing the extra space, but should be good to go!

**Review by zanieb — COMMENTED** [review]
(attempting to remove this from my review queue)

**Pull request closed without merging**
