### PR TITLE
Improve tests verifying correct installation

### PR DESCRIPTION
**Pull request by madkinsz**
- Checks that the version number is correct
- Checks that the long-form version command can be run, which pulls information about the client and database

### CODE REVIEW

**Comment by madkinsz** [comment]
@Sahiler fyi this fails with

```
+ pip check
prefect 2.0.1 has requirement readchar>=3.0.5, but you have readchar 0.0.0-local.
```

**Comment by madkinsz** [comment]
See https://github.com/pypa/pip/pull/11159 for `pip check` flag to ignore packages.

**Comment by madkinsz** [comment]
Failing with
```
import: 'prefect.cli'
+ prefect version
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/prefect_1659548205466/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/prefect", line 6, in <module>
    from prefect.cli import cli
ImportError: cannot import name 'cli' from 'prefect.cli' (/home/conda/feedstock_root/build_artifacts/prefect_1659548205466/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/prefect/cli/__init__.py)
Tests failed for prefect-2.0.2-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for prefect-2.0.2-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: prefect-2.0.2-pyhd8ed1ab_0.tar.bz2
```

I'm guessing 2.0.2 is broken still due to this issue.

**Comment by Sahiler** [comment]
I am curious what changes are resulting in a failure in the CI pipeline, as importing prefect.cli works in this azure run https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=545573&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1566, going to continue looking into the cause

**Comment by madkinsz** [comment]
@Sahiler I believe the failure here is actually on the `prefect version` command where conda has generated a script that calls `from prefect.cli import cli`

**Pull request merged**
