### PR TITLE
Update typer pins

### PR DESCRIPTION
**Pull request by mikeoconnor0308**
Update typer pins to align with pins set for pip upstream in prefect as of [v2.19.8](https://github.com/PrefectHQ/prefect/blob/2.19.8/requirements.txt)

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterbygrave** [comment]
@mikeoconnor0308 Please can you bump the build number to `number: 1`

**Comment by cicdw** [comment]
The link in the PR comment references prefect's 3.x version which does have different requirements than the 2.x builds currently happening in conda-forge, but in this case the change is also inline with upstream 2.x requirements.  Commenting here mainly for future reference 👍

**Comment by mikeoconnor0308** [comment]
> The link in the PR comment references prefect's 3.x version which does have different requirements than the 2.x builds currently happening in conda-forge, but in this case the change is also inline with upstream 2.x requirements. Commenting here mainly for future reference 👍

thanks, updated the description with link to 2.19.8

**Review by cicdw — APPROVED** [review]

**Comment by jakirkham** [comment]
CI is not running. We will need to restart `main` when it is resolved

More details in issue: https://github.com/conda-forge/status/issues/184

**Comment by jakirkham** [comment]
Looks like Azure built on `main`

Please recheck though

**Pull request merged**
