### PR TITLE
Add maintainers [ci skip]

### PR DESCRIPTION
**Pull request by dhirschfeld**
Closes https://github.com/PrefectHQ/prefect/issues/835

### CODE REVIEW

**Comment by jlowin** [comment]
cc @cicdw

**Comment by dhirschfeld** [comment]
***Attn:*** @jlowin, @cicdw 

Let me know if either/both of you would like to be added as maintainers? If not we can simply close this PR.

**Comment by dhirschfeld** [comment]
I'm calling it a day down here, so I won't get around to merging this until the morning...

**Comment by cicdw** [comment]
I'd like to be added as a maintainer

**Comment by jlowin** [comment]
You can leave me out for now if you don't mind.

**Comment by dhirschfeld** [comment]
Done & done!

**Pull request merged**
